name: "Setup environment"
description: "Sets up environment for stardis and caches it"

inputs:
  os-label:
    description: "os label for lock file, default linux"
    required: true
    default: "linux-64"

runs:
  using: "composite"
  steps:
      - name: Download Lock File
        run:  wget -q https://raw.githubusercontent.com/stardis-sn/stardis/main/conda-${{ inputs.os-label }}.lock
        shell: bash
      
      - name: Generate Cache Key
        run: | 
          file_hash=$(cat conda-${{ inputs.os-label }}.lock | shasum -a 256 | cut -d' ' -f1)
          echo "file_hash=stardis-conda-env-${{ inputs.os-label }}-${file_hash}-v1" >> "${GITHUB_OUTPUT}"
        id: cache-environment-key
        shell: bash
        
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: conda-${{ inputs.os-label }}.lock
          cache-environment-key: ${{ steps.cache-environment-key.outputs.file_hash }}
          cache-downloads-key: ${{ steps.cache-environment-key.outputs.file_hash }}
          environment-name: stardis
          cache-environment: true
          cache-downloads: true
