name: release

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch: # manual trigger

defaults:
  run:
    shell: bash -l {0}


jobs:
  pip_tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  zenodo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: tardis-sn/tardis_zenodo	
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Lock File
        run:  wget -q https://raw.githubusercontent.com/tardis-sn/stardis/master/conda-linux-64.lock

      - name: Generate Cache Key
        run: | 
            file_hash=$(cat conda-linux-64.lock | shasum -a 256 | cut -d' ' -f1)
            echo "file_hash=$file_hash" >> "${GITHUB_OUTPUT}"
        id: cache-environment-key

      - uses: mamba-org/setup-micromamba@v2
        with:
            environment-file: conda-linux-64.lock
            cache-environment-key: ${{ steps.cache-environment-key.outputs.file_hash }}
            cache-downloads-key: ${{ steps.cache-environment-key.outputs.file_hash }}
            environment-name: tardis
            cache-environment: true
            cache-downloads: true

      - name: Dump Secret Key
        run: echo "$KEY_SECRET_JSON" > key_secret.json
        env:
          KEY_SECRET_JSON: ${{ secrets.ZENODO_KEY_SECRET_JSON }}

      - name: Run Notebook
        run: jupyter nbconvert gather_data.ipynb --to html --execute --ExecutePreprocessor.timeout=6000

      - name: Run Notebook (allow errors)
        run: jupyter nbconvert gather_data.ipynb --to html --execute --ExecutePreprocessor.timeout=6000 --allow-errors
        if: failure()

      - uses: actions/upload-artifact@v4
        with:
          name: zenodo_json
          path: .zenodo.json

  create:
    needs: [pip_tests, zenodo]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install setuptools_scm
        run: pip install "setuptools_scm<7" git-cliff==2.6.1

      - name: Show current version
        run: python .ci-helpers/get_current_version.py

      - name: Get next version
        run: |
          python .ci-helpers/get_next_version.py
          echo "NEW_TAG=$(python .ci-helpers/get_next_version.py)" >> $GITHUB_ENV
      - name: Initialize release
        uses: softprops/action-gh-release@v1
        with:
          name: Stardis v${{ env.NEW_TAG }}
          tag_name: release-${{ env.NEW_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "This release has been created automatically by the STARDIS continuous delivery pipeline."
          draft: false

      - name: Wait for Zenodo to update the latest release
        run: sleep 120

      - name: Fetch Latest DOI from Zenodo
        id: fetch-doi
        run: |
            CONCEPT_DOI="15677112"
            # Make the API request for BibTeX format, following redirects
            response=$(curl -s -L -H "Accept: application/x-bibtex" "https://zenodo.org/api/records/${CONCEPT_DOI}")
        
            # Extract the full DOI value correctly
            doi=$(echo "$response" | grep -oP 'doi\s*=\s*{([^}]+)}' | grep -oP '\{([^}]+)\}' | sed 's/[{}]//g')
        
            # Extract the DOI URL directly from the response
            url=$(echo "$response" | grep -oP 'url\s*=\s*{([^}]+)}' | grep -oP '\{([^}]+)\}' | sed 's/[{}]//g')
        
            echo "Extracted DOI: ${doi}"
            echo "Extracted URL: ${url}"
            # Create DOI badge using the full DOI value
            doi_badge="[![DOI Badge](https://img.shields.io/badge/DOI-${doi}-blue)](${url})"
        
            # Store results in GitHub environment variables
            echo "doi_badge=${doi_badge}" >> $GITHUB_ENV
            echo "doi_url=${url}" >> $GITHUB_ENV
        
      - name: Generate and process changelog
        run: |
          CHANGELOG=$(git cliff --config pyproject.toml --unreleased --tag ${{ env.NEW_TAG }} | sed -n '/^## Changelog/,$p' | grep -vE '^(ERROR|WARN)')
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Update release with changelog and DOI
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ env.NEW_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            This release has been created automatically by the STARDIS continuous delivery pipeline.
            ${{ env.doi_badge }}
            ${{ env.CHANGELOG }}
          files: |
            conda-osx-arm64.lock
            conda-linux-64.lock
            conda-lock.yml
          fail_on_unmatched_files: false
          draft: false